#!/bin/bash

# do not just run this script
return 1

# steps to fetch the nginx ingress stuff
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

export CHART_VERSION="4.13.0"
export APP_VERSION="1.13.0"

helm template ingress-nginx ingress-nginx \
	--repo https://kubernetes.github.io/ingress-nginx \
	--version ${CHART_VERSION} \
	--namespace ingress-nginx \
	> ~/projects/prefect-server/manifests/nginx-ingress.${APP_VERSION}.yaml

kubectl create namespace ingress-nginx
kubectl apply -f ~/projects/prefect-server/manifests/nginx-ingress.${APP_VERSION}.yaml

